import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly, NetworkFirst } from 'workbox-strategies';

clientsClaim();
self.skipWaiting();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Background Sync Queue for offline expense creations
const bgSyncPlugin = new BackgroundSyncPlugin('expense-queue', {
  maxRetentionTime: 24 * 60, // Retry for max of 24 Hours (specified in minutes)
});

// Cache GET requests (Network First)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/expenses') && url.origin.includes('localhost'),
  new NetworkFirst({
    cacheName: 'api-cache',
  }),
  'GET'
);

// Queue POST/PUT/DELETE requests when offline
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/expenses') && url.origin.includes('localhost'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'POST'
);

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/expenses') && url.origin.includes('localhost'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'DELETE'
);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
